// mdot	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// wxwz	
// krra	 By downloading, copying, installing or using the software you agree to this license.
// bmgr	 If you do not agree to this license, do not download, install,
// imcz	 copy or use the software.
// qebq	
// uakb	                          License Agreement
// gwnh	         For OpenVss - Open Source Video Surveillance System
// goqb	
// xoyh	Copyright (C) 2007-2009, Prince of Songkla University, All rights reserved.
// omib	
// xpdf	Third party copyrights are property of their respective owners.
// ccrh	
// xwjh	Redistribution and use in source and binary forms, with or without modification,
// cxyw	are permitted provided that the following conditions are met:
// mvso	
// ejtn	  * Redistribution's of source code must retain the above copyright notice,
// vetu	    this list of conditions and the following disclaimer.
// nuke	
// watf	  * Redistribution's in binary form must reproduce the above copyright notice,
// xfye	    this list of conditions and the following disclaimer in the documentation
// ffjk	    and/or other materials provided with the distribution.
// ejza	
// pcvt	  * Neither the name of the copyright holders nor the names of its contributors 
// ttwn	    may not be used to endorse or promote products derived from this software 
// vpjy	    without specific prior written permission.
// iwtd	
// lfkb	This software is provided by the copyright holders and contributors "as is" and
// dtzg	any express or implied warranties, including, but not limited to, the implied
// xoiz	warranties of merchantability and fitness for a particular purpose are disclaimed.
// aijm	In no event shall the Prince of Songkla University or contributors be liable 
// ftfl	for any direct, indirect, incidental, special, exemplary, or consequential damages
// zrkc	(including, but not limited to, procurement of substitute goods or services;
// dfjh	loss of use, data, or profits; or business interruption) however caused
// wavj	and on any theory of liability, whether in contract, strict liability,
// lgzy	or tort (including negligence or otherwise) arising in any way out of
// zxwv	the use of this software, even if advised of the possibility of such damage.

namespace VsStreamerTest.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsStreamerTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
