// irbf	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// wdma	
// brui	 By downloading, copying, installing or using the software you agree to this license.
// qfjm	 If you do not agree to this license, do not download, install,
// xzio	 copy or use the software.
// hdpx	
// cubb	                          License Agreement
// uszo	         For OpenVss - Open Source Video Surveillance System
// butm	
// eeqx	Copyright (C) 2007-2009, Prince of Songkla University, All rights reserved.
// hzbs	
// eioq	Third party copyrights are property of their respective owners.
// hghc	
// yxwe	Redistribution and use in source and binary forms, with or without modification,
// bddb	are permitted provided that the following conditions are met:
// ckfi	
// sggv	  * Redistribution's of source code must retain the above copyright notice,
// lwit	    this list of conditions and the following disclaimer.
// jkhh	
// bxtu	  * Redistribution's in binary form must reproduce the above copyright notice,
// fkun	    this list of conditions and the following disclaimer in the documentation
// lxpd	    and/or other materials provided with the distribution.
// yolb	
// aovw	  * Neither the name of the copyright holders nor the names of its contributors 
// tsay	    may not be used to endorse or promote products derived from this software 
// btek	    without specific prior written permission.
// yoso	
// qocd	This software is provided by the copyright holders and contributors "as is" and
// kjvr	any express or implied warranties, including, but not limited to, the implied
// prxu	warranties of merchantability and fitness for a particular purpose are disclaimed.
// qcxw	In no event shall the Prince of Songkla University or contributors be liable 
// lhsu	for any direct, indirect, incidental, special, exemplary, or consequential damages
// olnj	(including, but not limited to, procurement of substitute goods or services;
// xusm	loss of use, data, or profits; or business interruption) however caused
// fjpx	and on any theory of liability, whether in contract, strict liability,
// ebnk	or tort (including negligence or otherwise) arising in any way out of
// lhqr	the use of this software, even if advised of the possibility of such damage.

namespace VsSetup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsSetup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap loading_aqua {
            get {
                object obj = ResourceManager.GetObject("loading_aqua", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
