// samp	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// bbfr	
// xdbb	 By downloading, copying, installing or using the software you agree to this license.
// dtip	 If you do not agree to this license, do not download, install,
// buyw	 copy or use the software.
// lerd	
// egoh	                          License Agreement
// pxle	         For OpenVSS - Open Source Video Surveillance System
// kqyk	
// jtty	Copyright (C) 2007-2010, Prince of Songkla University, All rights reserved.
// cigw	
// blzn	Third party copyrights are property of their respective owners.
// apih	
// fojo	Redistribution and use in source and binary forms, with or without modification,
// ijku	are permitted provided that the following conditions are met:
// nxbz	
// rxrn	  * Redistribution's of source code must retain the above copyright notice,
// vxfi	    this list of conditions and the following disclaimer.
// batc	
// xvct	  * Redistribution's in binary form must reproduce the above copyright notice,
// haga	    this list of conditions and the following disclaimer in the documentation
// peyw	    and/or other materials provided with the distribution.
// hkca	
// iykf	  * Neither the name of the copyright holders nor the names of its contributors 
// ggfd	    may not be used to endorse or promote products derived from this software 
// tmrd	    without specific prior written permission.
// jafe	
// ugqn	This software is provided by the copyright holders and contributors "as is" and
// hqnm	any express or implied warranties, including, but not limited to, the implied
// qbkm	warranties of merchantability and fitness for a particular purpose are disclaimed.
// yvfl	In no event shall the Prince of Songkla University or contributors be liable 
// vfzd	for any direct, indirect, incidental, special, exemplary, or consequential damages
// qowq	(including, but not limited to, procurement of substitute goods or services;
// qyzv	loss of use, data, or profits; or business interruption) however caused
// jdrp	and on any theory of liability, whether in contract, strict liability,
// ztca	or tort (including negligence or otherwise) arising in any way out of
// totr	the use of this software, even if advised of the possibility of such damage.
// kxoe	
// wsey	Intelligent Systems Laboratory (iSys Lab)
// ggid	Faculty of Engineering, Prince of Songkla University, THAILAND
// acof	Project leader by Nikom SUVONVORN
// kzxi	Project website at http://code.google.com/p/openvss/

namespace VsMediaProxyServerWinServiceControl.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsMediaProxyServerWinServiceControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
