// pehe	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// naog	
// kuuu	 By downloading, copying, installing or using the software you agree to this license.
// upiz	 If you do not agree to this license, do not download, install,
// yqct	 copy or use the software.
// ixyb	
// ijiy	                          License Agreement
// mejy	         For OpenVSS - Open Source Video Surveillance System
// cvni	
// gwwb	Copyright (C) 2007-2010, Prince of Songkla University, All rights reserved.
// yqac	
// wnuw	Third party copyrights are property of their respective owners.
// kjmf	
// pvzs	Redistribution and use in source and binary forms, with or without modification,
// ggvd	are permitted provided that the following conditions are met:
// squg	
// lwsz	  * Redistribution's of source code must retain the above copyright notice,
// bzsb	    this list of conditions and the following disclaimer.
// taus	
// wveu	  * Redistribution's in binary form must reproduce the above copyright notice,
// ploc	    this list of conditions and the following disclaimer in the documentation
// rdig	    and/or other materials provided with the distribution.
// vvcz	
// asji	  * Neither the name of the copyright holders nor the names of its contributors 
// wuqa	    may not be used to endorse or promote products derived from this software 
// vuvk	    without specific prior written permission.
// qklp	
// agvk	This software is provided by the copyright holders and contributors "as is" and
// caog	any express or implied warranties, including, but not limited to, the implied
// brpi	warranties of merchantability and fitness for a particular purpose are disclaimed.
// oldf	In no event shall the Prince of Songkla University or contributors be liable 
// xsab	for any direct, indirect, incidental, special, exemplary, or consequential damages
// rmwb	(including, but not limited to, procurement of substitute goods or services;
// fezv	loss of use, data, or profits; or business interruption) however caused
// qelg	and on any theory of liability, whether in contract, strict liability,
// rtgp	or tort (including negligence or otherwise) arising in any way out of
// arxa	the use of this software, even if advised of the possibility of such damage.
// edge	
// filk	Intelligent Systems Laboratory (iSys Lab)
// qpmy	Faculty of Engineering, Prince of Songkla University, THAILAND
// jkxo	Project leader by Nikom SUVONVORN
// ktfx	Project website at http://code.google.com/p/openvss/

namespace VsMobile.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsMobile.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
