#region Using directives

using System;

#endregion

namespace Vs.Encoder.WmvLib.WMFSDKWrapper
{
	[Flags]
	public enum WMT_CONTENT_TYPE
	{
		WMT_NONE = 0,
		WMT_AUDIO = 1,
		WMT_VIDEO = 16,
		WMT_SCRIPT = 256,
		WMT_HTML = 4096
	}

	[Flags]
	public enum WMT_STREAM_SAMPLE_TYPE
	{
		WM_SF_CLEANPOINT = 0x1,
		WM_SF_DISCONTINUITY = 0x2,
		WM_SF_DATALOSS = 0x4
	}

	public enum WMT_STREAM_SELECTION
	{
		WMT_OFF = 0,
		WMT_CLEANPOINT_ONLY = 1,
		WMT_ON = 2,
	}

	public enum WMT_ATTR_DATATYPE
	{
		WMT_TYPE_DWORD = 0,
		WMT_TYPE_STRING = 1,
		WMT_TYPE_BINARY = 2,
		WMT_TYPE_BOOL = 3,
		WMT_TYPE_QWORD = 4,
		WMT_TYPE_WORD = 5,
		WMT_TYPE_GUID = 6,
	}

	public enum WMT_VERSION
	{
		WMT_VER_4_0 = 0x00040000,
		WMT_VER_7_0 = 0x00070000,
		WMT_VER_8_0 = 0x00080000,
		WMT_VER_9_0 = 0x00090000,
	}

	public enum WMT_STORAGE_FORMAT
	{
		WMT_Storage_Format_MP3,
		WMT_Storage_Format_V1
	}

	public enum WMT_TRANSPORT_TYPE
	{
		WMT_Transport_Type_Unreliable,
		WMT_Transport_Type_Reliable
	}

	public enum WMT_STATUS
	{
		WMT_ERROR = 0,
		WMT_OPENED = 1,
		WMT_BUFFERING_START = 2,
		WMT_BUFFERING_STOP = 3,
		WMT_EOF = 4,
		WMT_END_OF_FILE = 4,
		WMT_END_OF_SEGMENT = 5,
		WMT_END_OF_STREAMING = 6,
		WMT_LOCATING = 7,
		WMT_CONNECTING = 8,
		WMT_NO_RIGHTS = 9,
		WMT_MISSING_CODEC = 10,
		WMT_STARTED = 11,
		WMT_STOPPED = 12,
		WMT_CLOSED = 13,
		WMT_STRIDING = 14,
		WMT_TIMER = 15,
		WMT_INDEX_PROGRESS = 16,
		WMT_SAVEAS_START = 17,
		WMT_SAVEAS_STOP = 18,
		WMT_NEW_SOURCEFLAGS = 19,
		WMT_NEW_METADATA = 20,
		WMT_BACKUPRESTORE_BEGIN = 21,
		WMT_SOURCE_SWITCH = 22,
		WMT_ACQUIRE_LICENSE = 23,
		WMT_INDIVIDUALIZE = 24,
		WMT_NEEDS_INDIVIDUALIZATION = 25,
		WMT_NO_RIGHTS_EX = 26,
		WMT_BACKUPRESTORE_END = 27,
		WMT_BACKUPRESTORE_CONNECTING = 28,
		WMT_BACKUPRESTORE_DISCONNECTING = 29,
		WMT_ERROR_WITHURL = 30,
		WMT_RESTRICTED_LICENSE = 31,
		WMT_CLIENT_CONNECT = 32,
		WMT_CLIENT_DISCONNECT = 33,
		WMT_NATIVE_OUTPUT_PROPS_CHANGED = 34,
		WMT_RECONNECT_START = 35,
		WMT_RECONNECT_END = 36,
		WMT_CLIENT_CONNECT_EX = 37,
		WMT_CLIENT_DISCONNECT_EX = 38,
		WMT_SET_FEC_SPAN = 39,
		WMT_PREROLL_READY = 40,
		WMT_PREROLL_COMPLETE = 41,
		WMT_CLIENT_PROPERTIES = 42,
		WMT_LICENSEURL_SIGNATURE_STATE = 43
	}

	public enum WMT_PLAY_MODE
	{
		WMT_PLAY_MODE_AUTOSELECT = 0,
		WMT_PLAY_MODE_LOCAL = 1,
		WMT_PLAY_MODE_DOWNLOAD = 2,
		WMT_PLAY_MODE_STREAMING = 3,
	}

	public enum WMT_OFFSET_FORMAT
	{
		WMT_OFFSET_FORMAT_100NS,
		WMT_OFFSET_FORMAT_FRAME_NUMBERS,
		WMT_OFFSET_FORMAT_PLAYLIST_OFFSET,
		WMT_OFFSET_FORMAT_TIMECODE
	}

	public enum WMT_CODEC_INFO_TYPE : uint
	{
		WMT_CODECINFO_AUDIO = 0,
		WMT_CODECINFO_VIDEO = 1,
		WMT_CODECINFO_UNKNOWN = 0xFFFFFFFF,
	}

	[Flags]
	public enum WMT_RIGHTS : uint
	{
		WMT_RIGHT_NO_DRM = 0x00000000,
		WMT_RIGHT_PLAYBACK = 0x00000001,
		WMT_RIGHT_COPY_TO_NON_SDMI_DEVICE = 0x00000002,
		WMT_RIGHT_COPY_TO_CD = 0x00000008,
		WMT_RIGHT_COPY_TO_SDMI_DEVICE = 0x00000010,
		WMT_RIGHT_ONE_TIME = 0x00000020,
		WMT_RIGHT_SAVE_STREAM_PROTECTED = 0x00000040,
		WMT_RIGHT_SDMI_TRIGGER = 0x00010000,
		WMT_RIGHT_SDMI_NOMORECOPIES = 0x00020000
	}

	public enum WMT_INDEXER_TYPE
	{
		WMT_IT_PRESENTATION_TIME,
		WMT_IT_FRAME_NUMBERS,
		WMT_IT_TIMECODE
	}

	public enum WMT_INDEX_TYPE
	{
		WMT_IT_NEAREST_DATA_UNIT = 1,
		WMT_IT_NEAREST_OBJECT,
		WMT_IT_NEAREST_CLEAN_POINT
	}

	public enum WMT_NET_PROTOCOL
	{
		WMT_PROTOCOL_HTTP = 0,
	}
}
