// huag	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// yvou	
// ongd	 By downloading, copying, installing or using the software you agree to this license.
// vadl	 If you do not agree to this license, do not download, install,
// djvc	 copy or use the software.
// warb	
// bhhz	                          License Agreement
// njyg	         For OpenVSS - Open Source Video Surveillance System
// mool	
// lcpx	Copyright (C) 2007-2010, Prince of Songkla University, All rights reserved.
// inmz	
// xzud	Third party copyrights are property of their respective owners.
// fefm	
// zayh	Redistribution and use in source and binary forms, with or without modification,
// czfq	are permitted provided that the following conditions are met:
// nphf	
// ozrh	  * Redistribution's of source code must retain the above copyright notice,
// msab	    this list of conditions and the following disclaimer.
// uxui	
// nsdb	  * Redistribution's in binary form must reproduce the above copyright notice,
// neti	    this list of conditions and the following disclaimer in the documentation
// dmhm	    and/or other materials provided with the distribution.
// qhjl	
// wyks	  * Neither the name of the copyright holders nor the names of its contributors 
// fglx	    may not be used to endorse or promote products derived from this software 
// imrn	    without specific prior written permission.
// desb	
// gptk	This software is provided by the copyright holders and contributors "as is" and
// vddi	any express or implied warranties, including, but not limited to, the implied
// wzcc	warranties of merchantability and fitness for a particular purpose are disclaimed.
// rfrf	In no event shall the Prince of Songkla University or contributors be liable 
// ioev	for any direct, indirect, incidental, special, exemplary, or consequential damages
// mbdh	(including, but not limited to, procurement of substitute goods or services;
// hfta	loss of use, data, or profits; or business interruption) however caused
// nfez	and on any theory of liability, whether in contract, strict liability,
// tffb	or tort (including negligence or otherwise) arising in any way out of
// nzqt	the use of this software, even if advised of the possibility of such damage.
// vcvf	
// eigd	Intelligent Systems Laboratory (iSys Lab)
// vmep	Faculty of Engineering, Prince of Songkla University, THAILAND
// zxpe	Project leader by Nikom SUVONVORN
// lldp	Project website at http://code.google.com/p/openvss/

namespace Vs.MediaProxyServer.Application.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vs.MediaProxyServer.Application.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
