// ydob	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// ikum	
// gmye	 By downloading, copying, installing or using the software you agree to this license.
// fdfq	 If you do not agree to this license, do not download, install,
// htmm	 copy or use the software.
// zots	
// qqlb	                          License Agreement
// gkjo	         For OpenVss - Open Source Video Surveillance System
// xola	
// sowy	Copyright (C) 2007-2009, Prince of Songkla University, All rights reserved.
// jmkw	
// odym	Third party copyrights are property of their respective owners.
// setg	
// rnzk	Redistribution and use in source and binary forms, with or without modification,
// jwlr	are permitted provided that the following conditions are met:
// ytgw	
// dkgr	  * Redistribution's of source code must retain the above copyright notice,
// rfxt	    this list of conditions and the following disclaimer.
// wndm	
// dxdm	  * Redistribution's in binary form must reproduce the above copyright notice,
// szib	    this list of conditions and the following disclaimer in the documentation
// rdwj	    and/or other materials provided with the distribution.
// obqw	
// dfzp	  * Neither the name of the copyright holders nor the names of its contributors 
// gnte	    may not be used to endorse or promote products derived from this software 
// xgun	    without specific prior written permission.
// gzje	
// kmhl	This software is provided by the copyright holders and contributors "as is" and
// syzz	any express or implied warranties, including, but not limited to, the implied
// lefz	warranties of merchantability and fitness for a particular purpose are disclaimed.
// nwdp	In no event shall the Prince of Songkla University or contributors be liable 
// obqr	for any direct, indirect, incidental, special, exemplary, or consequential damages
// nngp	(including, but not limited to, procurement of substitute goods or services;
// eyom	loss of use, data, or profits; or business interruption) however caused
// euvr	and on any theory of liability, whether in contract, strict liability,
// tszb	or tort (including negligence or otherwise) arising in any way out of
// uede	the use of this software, even if advised of the possibility of such damage.

namespace InsertAssemblyInfo.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InsertAssemblyInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
