// mdzd	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// elig	
// zyoq	 By downloading, copying, installing or using the software you agree to this license.
// dueo	 If you do not agree to this license, do not download, install,
// gsaq	 copy or use the software.
// jtju	
// luam	                          License Agreement
// rpus	         For OpenVSS - Open Source Video Surveillance System
// yubb	
// mgfi	Copyright (C) 2007-2010, Prince of Songkla University, All rights reserved.
// eigp	
// guah	Third party copyrights are property of their respective owners.
// unfy	
// uzdt	Redistribution and use in source and binary forms, with or without modification,
// tesj	are permitted provided that the following conditions are met:
// kvpk	
// evsi	  * Redistribution's of source code must retain the above copyright notice,
// tdcz	    this list of conditions and the following disclaimer.
// mrmb	
// muoq	  * Redistribution's in binary form must reproduce the above copyright notice,
// utse	    this list of conditions and the following disclaimer in the documentation
// kwyy	    and/or other materials provided with the distribution.
// rhhh	
// ovxi	  * Neither the name of the copyright holders nor the names of its contributors 
// twlk	    may not be used to endorse or promote products derived from this software 
// crnr	    without specific prior written permission.
// lflc	
// nbhz	This software is provided by the copyright holders and contributors "as is" and
// pcpr	any express or implied warranties, including, but not limited to, the implied
// dkzh	warranties of merchantability and fitness for a particular purpose are disclaimed.
// wtrm	In no event shall the Prince of Songkla University or contributors be liable 
// vulq	for any direct, indirect, incidental, special, exemplary, or consequential damages
// tdiq	(including, but not limited to, procurement of substitute goods or services;
// jeod	loss of use, data, or profits; or business interruption) however caused
// fate	and on any theory of liability, whether in contract, strict liability,
// kvlp	or tort (including negligence or otherwise) arising in any way out of
// aisl	the use of this software, even if advised of the possibility of such damage.
// ggfi	
// wdni	Intelligent Systems Laboratory (iSys Lab)
// zbwq	Faculty of Engineering, Prince of Songkla University, THAILAND
// uvjj	Project leader by Nikom SUVONVORN
// sqpl	Project website at http://code.google.com/p/openvss/

namespace VsOperator.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsOperator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
