// wcsp	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// qpir	
// nlvq	 By downloading, copying, installing or using the software you agree to this license.
// bylx	 If you do not agree to this license, do not download, install,
// nhkf	 copy or use the software.
// rthu	
// dfpz	                          License Agreement
// jsvq	         For OpenVss - Open Source Video Surveillance System
// wvmx	
// sdby	Copyright (C) 2007-2009, Prince of Songkla University, All rights reserved.
// necx	
// ylby	Third party copyrights are property of their respective owners.
// tdfg	
// fkqc	Redistribution and use in source and binary forms, with or without modification,
// vymk	are permitted provided that the following conditions are met:
// ziiv	
// pfuf	  * Redistribution's of source code must retain the above copyright notice,
// mnfj	    this list of conditions and the following disclaimer.
// glrn	
// qjwr	  * Redistribution's in binary form must reproduce the above copyright notice,
// ergf	    this list of conditions and the following disclaimer in the documentation
// mplm	    and/or other materials provided with the distribution.
// fkcu	
// qqze	  * Neither the name of the copyright holders nor the names of its contributors 
// vhit	    may not be used to endorse or promote products derived from this software 
// rwmf	    without specific prior written permission.
// ywzu	
// sclm	This software is provided by the copyright holders and contributors "as is" and
// bvgh	any express or implied warranties, including, but not limited to, the implied
// cdia	warranties of merchantability and fitness for a particular purpose are disclaimed.
// thzb	In no event shall the Prince of Songkla University or contributors be liable 
// llsq	for any direct, indirect, incidental, special, exemplary, or consequential damages
// lnsj	(including, but not limited to, procurement of substitute goods or services;
// adzh	loss of use, data, or profits; or business interruption) however caused
// fagq	and on any theory of liability, whether in contract, strict liability,
// prtc	or tort (including negligence or otherwise) arising in any way out of
// yqsv	the use of this software, even if advised of the possibility of such damage.

namespace VsDbDeleteApp.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VsDbDeleteApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
