// kxcb	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// wnum	
// mybx	 By downloading, copying, installing or using the software you agree to this license.
// pojn	 If you do not agree to this license, do not download, install,
// ykjn	 copy or use the software.
// xhoi	
// rsix	                          License Agreement
// ayzi	         For OpenVSS - Open Source Video Surveillance System
// qihh	
// aeki	Copyright (C) 2007-2010, Prince of Songkla University, All rights reserved.
// twql	
// rrfm	Third party copyrights are property of their respective owners.
// jegx	
// lkpd	Redistribution and use in source and binary forms, with or without modification,
// juje	are permitted provided that the following conditions are met:
// exmo	
// ytgh	  * Redistribution's of source code must retain the above copyright notice,
// hcmu	    this list of conditions and the following disclaimer.
// aatb	
// rcqa	  * Redistribution's in binary form must reproduce the above copyright notice,
// nwnv	    this list of conditions and the following disclaimer in the documentation
// scwg	    and/or other materials provided with the distribution.
// tdxg	
// ufdw	  * Neither the name of the copyright holders nor the names of its contributors 
// kbmy	    may not be used to endorse or promote products derived from this software 
// lxeh	    without specific prior written permission.
// slwk	
// qnmg	This software is provided by the copyright holders and contributors "as is" and
// djrh	any express or implied warranties, including, but not limited to, the implied
// jqww	warranties of merchantability and fitness for a particular purpose are disclaimed.
// wzod	In no event shall the Prince of Songkla University or contributors be liable 
// egau	for any direct, indirect, incidental, special, exemplary, or consequential damages
// xwqp	(including, but not limited to, procurement of substitute goods or services;
// pspp	loss of use, data, or profits; or business interruption) however caused
// rgdg	and on any theory of liability, whether in contract, strict liability,
// gmpf	or tort (including negligence or otherwise) arising in any way out of
// rrcl	the use of this software, even if advised of the possibility of such damage.
// ownu	
// fqbl	Intelligent Systems Laboratory (iSys Lab)
// jadm	Faculty of Engineering, Prince of Songkla University, THAILAND
// lcnt	Project leader by Nikom SUVONVORN
// xwql	Project website at http://code.google.com/p/openvss/

namespace InsertAssemblyInfo.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if ((resourceMan == null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InsertAssemblyInfo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
    }
}
