// hxxp	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// tmzc	
// jwkc	 By downloading, copying, installing or using the software you agree to this license.
// mdxq	 If you do not agree to this license, do not download, install,
// xwdv	 copy or use the software.
// lpim	
// lrds	                          License Agreement
// wyvp	         For OpenVSS - Open Source Video Surveillance System
// dvkh	
// dskm	Copyright (C) 2007-2010, Prince of Songkla University, All rights reserved.
// aksr	
// kjdf	Third party copyrights are property of their respective owners.
// umys	
// ojqr	Redistribution and use in source and binary forms, with or without modification,
// olec	are permitted provided that the following conditions are met:
// iggk	
// avyr	  * Redistribution's of source code must retain the above copyright notice,
// sqnf	    this list of conditions and the following disclaimer.
// lrvb	
// xqbb	  * Redistribution's in binary form must reproduce the above copyright notice,
// nyyj	    this list of conditions and the following disclaimer in the documentation
// acbu	    and/or other materials provided with the distribution.
// ftsr	
// niet	  * Neither the name of the copyright holders nor the names of its contributors 
// ehro	    may not be used to endorse or promote products derived from this software 
// kmme	    without specific prior written permission.
// ztgw	
// npty	This software is provided by the copyright holders and contributors "as is" and
// jdpj	any express or implied warranties, including, but not limited to, the implied
// iwkx	warranties of merchantability and fitness for a particular purpose are disclaimed.
// temz	In no event shall the Prince of Songkla University or contributors be liable 
// xvrd	for any direct, indirect, incidental, special, exemplary, or consequential damages
// ncwq	(including, but not limited to, procurement of substitute goods or services;
// znqa	loss of use, data, or profits; or business interruption) however caused
// mtjh	and on any theory of liability, whether in contract, strict liability,
// wegq	or tort (including negligence or otherwise) arising in any way out of
// zuhk	the use of this software, even if advised of the possibility of such damage.
// tukh	
// wtvg	Intelligent Systems Laboratory (iSys Lab)
// amge	Faculty of Engineering, Prince of Songkla University, THAILAND
// bdjl	Project leader by Nikom SUVONVORN
// sdyw	Project website at http://code.google.com/p/openvss/

namespace Vs.License.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vs.License.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
    }
}
