// edxx	 IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING. 
// unes	
// gomw	 By downloading, copying, installing or using the software you agree to this license.
// eqvb	 If you do not agree to this license, do not download, install,
// ottc	 copy or use the software.
// afxy	
// phrp	                          License Agreement
// csia	         For OpenVSS - Open Source Video Surveillance System
// hyrn	
// wzrr	Copyright (C) 2007-2010, Prince of Songkla University, All rights reserved.
// sucx	
// pnlb	Third party copyrights are property of their respective owners.
// prio	
// ygwz	Redistribution and use in source and binary forms, with or without modification,
// fyim	are permitted provided that the following conditions are met:
// vpqo	
// gmog	  * Redistribution's of source code must retain the above copyright notice,
// yifo	    this list of conditions and the following disclaimer.
// bbkf	
// czic	  * Redistribution's in binary form must reproduce the above copyright notice,
// wpak	    this list of conditions and the following disclaimer in the documentation
// ktbb	    and/or other materials provided with the distribution.
// bshx	
// rfwd	  * Neither the name of the copyright holders nor the names of its contributors 
// eord	    may not be used to endorse or promote products derived from this software 
// zedg	    without specific prior written permission.
// mtnw	
// vrwf	This software is provided by the copyright holders and contributors "as is" and
// pfpf	any express or implied warranties, including, but not limited to, the implied
// pgem	warranties of merchantability and fitness for a particular purpose are disclaimed.
// kmfg	In no event shall the Prince of Songkla University or contributors be liable 
// ahxv	for any direct, indirect, incidental, special, exemplary, or consequential damages
// fgbo	(including, but not limited to, procurement of substitute goods or services;
// ifds	loss of use, data, or profits; or business interruption) however caused
// mtxq	and on any theory of liability, whether in contract, strict liability,
// gegk	or tort (including negligence or otherwise) arising in any way out of
// wbhl	the use of this software, even if advised of the possibility of such damage.
// pqoy	
// ketm	Intelligent Systems Laboratory (iSys Lab)
// zwgf	Faculty of Engineering, Prince of Songkla University, THAILAND
// vrro	Project leader by Nikom SUVONVORN
// pixk	Project website at http://code.google.com/p/openvss/

namespace Vs.Playback.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vs.Playback.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap control_end_blue {
            get {
                object obj = ResourceManager.GetObject("control_end_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_fastforward_blue {
            get {
                object obj = ResourceManager.GetObject("control_fastforward_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_pause_blue {
            get {
                object obj = ResourceManager.GetObject("control_pause_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_play_blue {
            get {
                object obj = ResourceManager.GetObject("control_play_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_repeat_blue {
            get {
                object obj = ResourceManager.GetObject("control_repeat_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_rewind_blue {
            get {
                object obj = ResourceManager.GetObject("control_rewind_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_start_blue {
            get {
                object obj = ResourceManager.GetObject("control_start_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap control_stop_blue {
            get {
                object obj = ResourceManager.GetObject("control_stop_blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap isys_color {
            get {
                object obj = ResourceManager.GetObject("isys_color", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap isyscolor {
            get {
                object obj = ResourceManager.GetObject("isyscolor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
